---
title: Een enkele pixel instellen op de Sense HAT
hero_image: images/banner.png
description: Leer hoe je pixels met coördinaten op de Sense HAT instelt
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "python"
steps:
  - 
    title: Stap een
