title: Setting a single pixel on the Sense HAT
hero_image: images/banner.png
description: Learn how to set pixels with coordinates on the Sense HAT
original_url:
theme: cc-prototype
duration: 1 # 1, 2 or 3
listed: false
ingredient: true
interests: ""
technologies: "python"
steps:
  - title: Step one
