---
title: Sense HAT पर एक पिक्सेल (pixel) सेट करना
hero_image: images/banner.png
description: Sense HAT पर समन्वय के साथ पिक्सेल (pixel) सेट करना सीखें
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "python"
steps:
  - 
    title: पहला चरण
