---
title: Setting a single pixel on the Sense HAT
hero_image: images/banner.png
description: Learn how to set pixels with coordinates on the Sense HAT
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "python"
steps:
  - 
    title: Step one
