---
title: Configurar un solo píxel en Sense HAT
hero_image: images/banner.png
description: Aprende a configurar píxeles a través de coordenadas en Sense HAT
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "python"
steps:
  - title: Paso uno
