---
title: Setze ein einzelnes Pixel auf dem Sense HAT
hero_image: images/banner.png
description: Erfahre, wie du Pixel mit Koordinaten im Sense HAT einstellen kannst
theme: rot #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "python"
steps:
  - 
    title: Schritt eins
