---
title: Configurando um único pixel no Sense HAT
hero_image: images/banner.png
description: Aprenda como definir pixels com coordenadas no Sense HAT
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "python"
steps:
  - title: Primeiro passo
