---
title: Ustawienie pojedynczego piksela w Sense HAT
hero_image: images/banner.png
description: Dowiedz się, jak ustawić piksele o współrzędnych w Sense HAT
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 # 1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "python"
steps:
  - title: Krok pierwszy
