---
title: Réglage d'un seul pixel sur le Sense HAT
hero_image: images/banner.png
description: Apprendre à définir des pixels avec des coordonnées sur le Sense HAT
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "python"
steps:
  - 
    title: Première étape
